version : "3"
services:
  web:
    build: .
    ports:
      - "80:80"
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: password
      DB_NAME: app
      APP_SECRET: "Bi9FYIPmqLJ6JaROOi1aphH/HHvMIg2YWnD3vhiVEG48G+SV"
   # volumes:
   #   - .:/var/app
  db:
    build: ./db
    environment:
      MYSQL_DATABASE: app
      MYSQL_ROOT_PASSWORD: password
